services:
  go-app:
    build: .
    image: devic-tarjetas-go:local
    ports:
      - "8000:8000"
    environment:
    - MONGO_URI=mongodb://mongodb:27017
    depends_on:
      - mongodb
    restart: no
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: