@API_URL = http://localhost:8000/api/debito
@ID_TEST = 6a0a15c7675bb036218fd464

### Ver TODAS las Cuentas (GET)
GET {{API_URL}}

### Crear Cuenta de Débito 
POST {{API_URL}}
Content-Type: application/json

{
  "nombre": "Banamex",
  "saldo": 1692.68
}


### Actualizar Cuenta 
PUT {{API_URL}}?id={{ID_TEST}}
Content-Type: application/json

{
  "nombre": "Banamex Nómina",
  "saldo": 5430.20
}


### Eliminar Cuenta
DELETE {{API_URL}}?id={{ID_TEST}}