@API_URL = http://localhost:8000/api/prestamo
@ID_TEST = 6a1203cb09ac7155ad432a88

### Crear Préstamo (POST)
POST {{API_URL}}
Content-Type: application/json

{
  "concepto": "Karla",
  "cantidad": 8487.50,
  "saldado": 0
}

### Ver TODOS los Préstamos 
GET {{API_URL}}


### Ver UN Préstamo por ID
GET {{API_URL}}?id={{ID_TEST}}

### Actualizar prestamo
PUT {{API_URL}}?id={{ID_TEST}}
Content-Type: application/json

{
  "concepto": "Karla",
  "cantidad": 8487.50,
  "saldado": 2000.00
}


### Eliminar Préstamo 
DELETE {{API_URL}}?id={{ID_TEST}}