@API_URL = http://localhost:8000/api/tarjetas
@ID_TEST = 6a0a15c7675bb036218fd464

## Ver las Tarjetas
GET {{API_URL}}


### Ver
GET {{API_URL}}?id={{ID_TEST}}

### Crear Tarjeta
Content-Type: application/json
POST {{API_URL}}
{
  "nombre": "Oro",
  "credito": 23700,
  "disponible": 18638.66,
  "saldo": 1692.68,
  "fechaPago": "2026-05-08",
  "saldoAPago": 572.52,
  "color": "#004481"
}

### Actualizar
PUT {{API_URL}}?id={{ID_TEST}}
Content-Type: application/json
{
  "nombre": "Oro",
  "credito": 25000,
  "disponible": 19000,
  "saldo": 1000,
  "fechaPago": "2026-05-08",
  "saldoAPago": 500,
  "color": "#004481"
}


### Borrar tarjeta
DELETE {{API_URL}}?id={{ID_TEST}}


################ Ejemplos de tarjetas para pruebas ################

### Crear Tarjeta: Joy
POST {{API_URL}}
Content-Type: application/json

{
  "nombre": "Joy",
  "credito": 19000,
  "disponible": 12239.91,
  "saldo": 2812.81,
  "fechaPago": "2026-05-11",
  "saldoAPago": 1612.9,
  "color": "#002D72"
}

### Crear Tarjeta: Rappi
POST {{API_URL}}
Content-Type: application/json

{
  "nombre": "Rappi",
  "credito": 52000,
  "disponible": 44502.14,
  "saldo": 2423.74,
  "fechaPago": "2026-05-27",
  "saldoAPago": 0,
  "color": "#FF5E3A"
}

### Crear Tarjeta: Plata
POST {{API_URL}}
Content-Type: application/json

{
  "nombre": "Plata",
  "credito": 3000,
  "disponible": 2612.65,
  "saldo": 387.35,
  "fechaPago": "2026-05-27",
  "saldoAPago": 387.35,
  "color": "#FF5D15"
}

### Crear Tarjeta: Nu
POST {{API_URL}}
Content-Type: application/json

{
  "nombre": "Nu",
  "credito": 16800,
  "disponible": 16434,
  "saldo": 366,
  "fechaPago": "2026-06-05",
  "saldoAPago": 0,
  "color": "#A63094"
}

### Crear Tarjeta: Klar
POST {{API_URL}}
Content-Type: application/json

{
  "nombre": "Klar",
  "credito": 20500,
  "disponible": 20158.93,
  "saldo": 341.07,
  "fechaPago": "2026-05-04",
  "saldoAPago": 341.07,
  "color": "#FF4D4D"
}

### Crear Tarjeta: Stori
POST {{API_URL}}
Content-Type: application/json

{
  "nombre": "Stori",
  "credito": 21000,
  "disponible": 17648,
  "saldo": 3352,
  "fechaPago": "2026-05-18",
  "saldoAPago": 111,
  "color": "#8A05BE"
}